Jolly-Lights-Cinema-Group/BusinessLogic/CustomerOrderService.cs, Jolly-Lights-Cinema-Group/BusinessLogic/DiscountCodeService.cs, Jolly-Lights-Cinema-Group/BusinessLogic/OrderLineService.cs, Jolly-Lights-Cinema-Group/BusinessLogic/ScheduleSeatService.cs, Jolly-Lights-Cinema-Group/DataAccess/CustomerOrderRepository.cs, Jolly-Lights-Cinema-Group/DataAccess/DiscountCodeRepository.cs, Jolly-Lights-Cinema-Group/DataAccess/OrderLineRepository.cs, Jolly-Lights-Cinema-Group/DataAccess/ScheduleSeatRepository.cs
Completed the setup of the database
=> Set up database

Jolly-Lights-Cinema-Group/Database/schema.sql
Nu kan de database ook echt worden aangemaakt via databasemanager.
=> fix few syntax mistakes in db schema

Jolly-Lights-Cinema-Group/DataAccess/DatabaseManager.cs, Jolly-Lights-Cinema-Group/Models/CustomerOrder.cs, Jolly-Lights-Cinema-Group/Models/DiscountCode.cs, Jolly-Lights-Cinema-Group/Models/MovieRoom.cs, Jolly-Lights-Cinema-Group/Models/OrderLine.cs, Jolly-Lights-Cinema-Group/Models/Reservation.cs, Jolly-Lights-Cinema-Group/Models/Schedule.cs, Jolly-Lights-Cinema-Group/Models/ScheduleSeat.cs
Made all the models.
- Customorder
- DiscountCode
- MovieRoom
- Orderline
- Reservation
- Schedule
- ScheduleSeat
=> Made the models for all the tables in schema.sql

Jolly-Lights-Cinema-Group/BusinessLogic/AdminHandler/AdminLocationHandler.cs, Jolly-Lights-Cinema-Group/BusinessLogic/LocationService.cs, Jolly-Lights-Cinema-Group/DataAccess/LocationRepository.cs, Jolly-Lights-Cinema-Group/PresentationLayer/Admin/AdminManageLocationsMenu.cs, Jolly-Lights-Cinema-Group/PresentationLayer/Admin/AdminMenu.cs, Jolly-Lights-Cinema-Group/PresentationLayer/LocationMenu.cs, JollyLights.Tests/JollyLights.Tests.csproj, JollyLights.Tests/TestLocationRepository.cs
In het Locatie management menu wil ik als admin gebruiker de naam en/of het address van een locatie kunnen wijzigen.
=> Locatie kunnen wijzigen in Locatie management menu

.gitignore, Jolly-Lights-Cinema-Group/BusinessLogic/AdminHandler/AdminUserHandler.cs, Jolly-Lights-Cinema-Group/BusinessLogic/EmployeeService.cs, Jolly-Lights-Cinema-Group/BusinessLogic/GlobalHandlers/AccountSettingsHandler.cs, Jolly-Lights-Cinema-Group/BusinessLogic/MovieService.cs, Jolly-Lights-Cinema-Group/DataAccess/DatabaseManager.cs, Jolly-Lights-Cinema-Group/DataAccess/EmployeeRepository.cs, Jolly-Lights-Cinema-Group/DataAccess/MovieRepository.cs, Jolly-Lights-Cinema-Group/PresentationLayer/Admin/AdminManageUsersMenu.cs, Jolly-Lights-Cinema-Group/PresentationLayer/Admin/AdminMenu.cs, Jolly-Lights-Cinema-Group/Program.cs, JollyLights.Tests/TestEmployeeRepository.cs, JollyLights.Tests/TestMovieRepository.cs
fixed the merge conflict.
Also added:
- movie unittests
- employee change email/password unittests
- implemented change email/password for employees
=> Fixed mergeconflict + added new methods

JollyLights.Tests/TestLocationRepository.cs
Een test die voor het aanpassen van een locatie. Test zowel de mogelijkheid om de naam en het address aan te passen, als maar 1 van de 2 aan te passen, waarbij de parameter die leeg blijft, name of address, hetzelfde blijft als die al was.
=> Test modifying a location

Jolly-Lights-Cinema-Group/DataAccess/DatabaseManager.cs, JollyLights.Tests/MSTestSettings.cs, JollyLights.Tests/TestEmployeeRepository.cs, JollyLights.Tests/TestLocationRepository.cs, JollyLights.Tests/TestMovieRepository.cs
Het doel is om voor de test folder een database in memory te maken. Hievoor moeten we kijken welk path hiervoor nodig is in de database manager.
=> Set up test database

Jolly-Lights-Cinema-Group/BusinessLogic/AdminHandler/AdminChoiceHandler.cs, Jolly-Lights-Cinema-Group/BusinessLogic/AuthenticationService.cs, Jolly-Lights-Cinema-Group/BusinessLogic/GlobalHandlers/AccountSettingsHandler.cs, Jolly-Lights-Cinema-Group/BusinessLogic/Manager Handler/ManagerChoiceHandler.cs, Jolly-Lights-Cinema-Group/PresentationLayer/Manager/ManagerMenu.cs, Jolly-Lights-Cinema-Group/Program.cs
Added the manager menu with working methods.
also made the change user information methods a bit more secure.
=> Added manager menu

Jolly-Lights-Cinema-Group/BusinessLogic/AdminHandler/AdminLocationHandler.cs, Jolly-Lights-Cinema-Group/BusinessLogic/LocationService.cs, Jolly-Lights-Cinema-Group/DataAccess/LocationRepository.cs, Jolly-Lights-Cinema-Group/PresentationLayer/LocationMenu.cs, Jolly-Lights-Cinema-Group/Tests/TestLocations.cs, JollyLights.Tests/TestLocationRepository.cs
Locatie management gebeurde eerst statisch, maar omdat dit in productie problemen oplevert met data die tegelijk binnen komt heb ik het weer non statisch gemaakt.
=> Make Location handlers non static

Jolly-Lights-Cinema-Group/BusinessLogic/AdminHandler/AdminMovieHandler.cs, Jolly-Lights-Cinema-Group/BusinessLogic/DiscountCodeService.cs, Jolly-Lights-Cinema-Group/BusinessLogic/MovieService.cs, Jolly-Lights-Cinema-Group/DataAccess/MovieRepository.cs, Jolly-Lights-Cinema-Group/Database/schema.sql, Jolly-Lights-Cinema-Group/Models/Movie.cs
added releasedate to the movie object.
=> Added releasedate to movie obj.

Jolly-Lights-Cinema-Group/BusinessLogic/AdminHandler/AdminChoiceHandler.cs, Jolly-Lights-Cinema-Group/BusinessLogic/CustomerOrderService.cs, Jolly-Lights-Cinema-Group/BusinessLogic/DiscountCodeService.cs, Jolly-Lights-Cinema-Group/BusinessLogic/Employee Handler/EmployeeChoiceHandler.cs, Jolly-Lights-Cinema-Group/BusinessLogic/GlobalHandlers/AccountSettingsHandler.cs, Jolly-Lights-Cinema-Group/BusinessLogic/GlobalHandlers/DiscountCodeHandler.cs, Jolly-Lights-Cinema-Group/BusinessLogic/GlobalHandlers/ReservationHandler.cs, Jolly-Lights-Cinema-Group/BusinessLogic/GlobalHandlers/ReservationNumber.cs, Jolly-Lights-Cinema-Group/BusinessLogic/Manager Handler/ManagerChoiceHandler.cs, Jolly-Lights-Cinema-Group/BusinessLogic/ReservationService.cs, Jolly-Lights-Cinema-Group/DataAccess/CustomerOrderRepository.cs, Jolly-Lights-Cinema-Group/DataAccess/DiscountCodeRepository.cs, Jolly-Lights-Cinema-Group/DataAccess/EmployeeRepository.cs, Jolly-Lights-Cinema-Group/DataAccess/LocationRepository.cs, Jolly-Lights-Cinema-Group/DataAccess/MovieRepository.cs, Jolly-Lights-Cinema-Group/DataAccess/ReservationRepository.cs, Jolly-Lights-Cinema-Group/Models/Reservation.cs, Jolly-Lights-Cinema-Group/PresentationLayer/ReservationMenu.cs, JollyLights.Tests/TestEmployeeRepository.cs, JollyLights.Tests/TestMovieRepository.cs, JollyLights.Tests/TestReservationMenu.cs
Ivm met dat in de prakrijk data met elkaar verwisseld kan worden als de repo of service statisch is, heb ik deze ook weer niet statisch gemaakt.
=> Reservation maken

Jolly-Lights-Cinema-Group/BusinessLogic/ScheduleSeatService.cs, Jolly-Lights-Cinema-Group/DataAccess/ScheduleSeatRepository.cs, Jolly-Lights-Cinema-Group/Enum/SeatType.cs, Jolly-Lights-Cinema-Group/Models/ScheduleSeat.cs, JollyLights.Tests/TestLocationRepository.cs, JollyLights.Tests/TestReservationMenu.cs
Ik heb een enum gemaakt voor de seat types, regular, love an vip. Hiernaast heb ik dit gelijk geimplementeerd in de ScheduleSeatService en Repository
=> Enum voor seattypes

Jolly-Lights-Cinema-Group/BusinessLogic/AdminHandler/AdminMovieHandler.cs, Jolly-Lights-Cinema-Group/BusinessLogic/MovieService.cs, Jolly-Lights-Cinema-Group/DataAccess/MovieRepository.cs, Jolly-Lights-Cinema-Group/PresentationLayer/Admin/AdminManageMovieMenu.cs, JollyLights.Tests/TestMovieRepository.cs
De mogelijkheid om oude films uit de database te halen is weggehaald.
=> Remove delete movie

Jolly-Lights-Cinema-Group/BusinessLogic/AdminHandler/AdminChoiceHandler.cs, Jolly-Lights-Cinema-Group/BusinessLogic/AdminHandler/AdminMovieHandler.cs, Jolly-Lights-Cinema-Group/BusinessLogic/Employee Handler/EmployeeChoiceHandler.cs, Jolly-Lights-Cinema-Group/BusinessLogic/GlobalHandlers/ReservationHandler.cs, Jolly-Lights-Cinema-Group/BusinessLogic/GlobalHandlers/ShopHandler.cs, Jolly-Lights-Cinema-Group/BusinessLogic/GlobalHandlers/ShopManagementHandler.cs, Jolly-Lights-Cinema-Group/BusinessLogic/Manager Handler/ManagerChoiceHandler.cs, Jolly-Lights-Cinema-Group/BusinessLogic/MovieService.cs, Jolly-Lights-Cinema-Group/BusinessLogic/ScheduleSeatService.cs, Jolly-Lights-Cinema-Group/BusinessLogic/ShopItemService.cs, Jolly-Lights-Cinema-Group/DataAccess/MovieRepository.cs, Jolly-Lights-Cinema-Group/DataAccess/ShopItemRepository.cs, Jolly-Lights-Cinema-Group/PresentationLayer/Admin/AdminManageMovieMenu.cs, Jolly-Lights-Cinema-Group/PresentationLayer/Admin/AdminMenu.cs, Jolly-Lights-Cinema-Group/PresentationLayer/Employee/EmployeeMenu.cs, Jolly-Lights-Cinema-Group/PresentationLayer/Manager/ManagerMenu.cs, Jolly-Lights-Cinema-Group/PresentationLayer/ShopManagementMenu.cs, JollyLights.Tests/TestMovieRepository.cs, JollyLights.Tests/TestScheduleShopItemRepository.cs, JollyLights.Tests/TestShop.cs, JollyLights.Tests/TestShopItemRepository.cs
Het shop management menu is zichtbaar voor elke gebruiker, employee, admin en manager. Hierin kunnen items worden toegevoegd aan de shop en worden geedit. Na alle informatie voor een reservering te hebben ingevuld kan je nog items toevoegen aan een reservering.
=> ShopManagement menu + Shop na reservering

Jolly-Lights-Cinema-Group/BusinessLogic/CustomerOrderService.cs, Jolly-Lights-Cinema-Group/BusinessLogic/GlobalHandlers/ReservationHandler.cs, Jolly-Lights-Cinema-Group/BusinessLogic/ReservationService.cs, Jolly-Lights-Cinema-Group/DataAccess/DatabaseManager.cs, Jolly-Lights-Cinema-Group/DataAccess/ReservationRepository.cs, Jolly-Lights-Cinema-Group/DataAccess/ScheduleSeatRepository.cs, Jolly-Lights-Cinema-Group/Jolly-Lights-Cinema-Group.csproj, Jolly-Lights-Cinema-Group/PresentationLayer/ReservationMenu.cs
Waneer je een reservering betaald wordt er een customer order aangemaakt + de totaalprijs word laten zien. Deze heeft ook geen merge conflicts meer.
=> create Customer order when paying an order

Jolly-Lights-Cinema-Group/BusinessLogic/CustomerOrderService.cs, Jolly-Lights-Cinema-Group/BusinessLogic/GlobalHandlers/ReservationHandler.cs, Jolly-Lights-Cinema-Group/BusinessLogic/ReservationService.cs, Jolly-Lights-Cinema-Group/BusinessLogic/ScheduleService.cs, Jolly-Lights-Cinema-Group/DataAccess/DatabaseManager.cs, Jolly-Lights-Cinema-Group/DataAccess/MovieRoomRepository.cs, Jolly-Lights-Cinema-Group/DataAccess/ReservationRepository.cs, Jolly-Lights-Cinema-Group/DataAccess/ScheduleRepository.cs, Jolly-Lights-Cinema-Group/DataAccess/ScheduleSeatRepository.cs, Jolly-Lights-Cinema-Group/Enum/MovieType.cs, Jolly-Lights-Cinema-Group/Jolly-Lights-Cinema-Group.csproj, Jolly-Lights-Cinema-Group/PresentationLayer/ReservationMenu.cs
Bij het maken van een reservering kies je eerst een film vervolgens een datum en dan een tijd, hierna kom je terecht bij het stoelen selecteren etc. Aan het einde van de reservering zie je een kort overzicht van het reserveringsnummer, de film datum en tijd en de geselecteerde stoel.
=> Reservation flow

Jolly-Lights-Cinema-Group/DataAccess/SeatRepository.cs, Jolly-Lights-Cinema-Group/Program.cs
Quick bug fix in seat reservation
=> Quick hotfix bug in make reservation  TOP 1 -> LIMIT 1

Jolly-Lights-Cinema-Group/BusinessLogic/AdminHandler/AdminMovieRoomHandler.cs, Jolly-Lights-Cinema-Group/Database/schema.sql
Hierdoor krijg ik niet meer de error invalid byte sequence.
=> Fix selecting files

JollyLights.Tests/TestEmployeeRepository.cs, JollyLights.Tests/TestLocationRepository.cs, JollyLights.Tests/TestMovieRepository.cs, JollyLights.Tests/TestMovieScheduleRepository.cs, JollyLights.Tests/TestReservationMenu.cs, JollyLights.Tests/TestScheduleShopItemRepository.cs, JollyLights.Tests/TestShop.cs, JollyLights.Tests/TestShopItemRepository.cs
Added the schedule test and fixed the multithreading bug from another issue.
=> Added Moviescheduletest and fixed the multhitreading bug

Jolly-Lights-Cinema-Group/BusinessLogic/OrderLineService.cs, Jolly-Lights-Cinema-Group/DataAccess/ReservationRepository.cs, Jolly-Lights-Cinema-Group/DataAccess/ScheduleSeatRepository.cs, Jolly-Lights-Cinema-Group/DataAccess/ShopItemRepository.cs
Van een schedule seat word nu een orderline aangemaakt. Deze zijn gegroepeerd op basis van het type stoel aangezien deze dezelfde prijs hebben. Bij Customer order bij het afrekenen worden nu ook de stoel prijzen opgeteld.
=> ScheduleSeat to order line

Jolly-Lights-Cinema-Group/BusinessLogic/GlobalHandlers/ReservationHandler.cs, Jolly-Lights-Cinema-Group/BusinessLogic/MovieRoomService.cs, Jolly-Lights-Cinema-Group/BusinessLogic/ScheduleService.cs, Jolly-Lights-Cinema-Group/BusinessLogic/ShopItemService.cs, Jolly-Lights-Cinema-Group/DataAccess/MovieRoomRepository.cs, Jolly-Lights-Cinema-Group/DataAccess/ScheduleRepository.cs, Jolly-Lights-Cinema-Group/Helpers/DateTimeValidator.cs, Jolly-Lights-Cinema-Group/PresentationLayer/Discountcode/ManageDiscountCode.cs, Jolly-Lights-Cinema-Group/PresentationLayer/Movie/ManageMovieMenu.cs, Jolly-Lights-Cinema-Group/PresentationLayer/Movie/MovieScheduleMenu.cs, Jolly-Lights-Cinema-Group/PresentationLayer/MovieRoom/ManageMovieRoomMenu.cs, Jolly-Lights-Cinema-Group/PresentationLayer/Schedule/ManageScheduleMenu.cs, Jolly-Lights-Cinema-Group/PresentationLayer/Schedule/MovieDateTimeMenu.cs, Jolly-Lights-Cinema-Group/PresentationLayer/Seats/ManageSeatsMenu.cs, Jolly-Lights-Cinema-Group/PresentationLayer/Shop/ShopManagementMenu.cs
Er kunnen nu ook schedules worden ingepland voor een al gemaakte schedule. Er word gekeken naar de starttijd van de nieuwe film + film duur + 15 min schoonmaaktijd. Als deze tijd clasht met het eerst volgende schedule op die dag, dan word er om een nieuwe tijd gevraagd en error message weergeven.
=> Check schedule free before

Jolly-Lights-Cinema-Group/PresentationLayer/Admin/AdminMenu.cs, Jolly-Lights-Cinema-Group/PresentationLayer/Employee/EmployeeMenu.cs, Jolly-Lights-Cinema-Group/PresentationLayer/Manager/ManagerMenu.cs, Jolly-Lights-Cinema-Group/PresentationLayer/Reservation/EditReservationMenu.cs, Jolly-Lights-Cinema-Group/PresentationLayer/Reservation/MakeReservationMenu.cs, Jolly-Lights-Cinema-Group/Program.cs
Bij het login scherm de promts: username: en password:, Veranderd naar: Enter username: en Enter password.
Manage Reservations veranderd naar Reservations.
Tussen haakjes "Save for later" toegevoegd achter het reserveringsnummer om duidelijk te maken dat het reserveringsnummer nog nodig is voor later om de reservering aan te passen of te betalen.
Optie toegevoegd om uit edit reservation te gaan door "C" van cancel in te typen en error messages toegevoegd.
=> Feedback van de user acceptance test van het reserveringsproces geimplementeerd

Jolly-Lights-Cinema-Group/PresentationLayer/Manager/ManagerMenu.cs, Jolly-Lights-Cinema-Group/PresentationLayer/Shop/CashDesk.cs
De manager kan nu ook gebruik maken van de kassa.
=> Geef manager de optie om de kassa te gebruiken

Jolly-Lights-Cinema-Group/PresentationLayer/Reservation/MakeReservationMenu.cs
Added user feedback to the reservation menu.
=> Adding error messages reservation menu

Jolly-Lights-Cinema-Group/Helpers/AgeVerifier.cs, Jolly-Lights-Cinema-Group/PresentationLayer/Movie/MovieScheduleMenu.cs, Jolly-Lights-Cinema-Group/PresentationLayer/Shop/CashDesk.cs, Jolly-Lights-Cinema-Group/PresentationLayer/Shop/ShopMenu.cs
Wanneer er uit de shop items worden toegevoegd met een minimum leeftijd wordt er gevraagd om de geboorte datum in te vullen wanneer de klant niet oud genoeg is kan het item niet worden gekocht. Voor films wordt er op leeftijd gecontroleert vanaf 16 plus films. Daarnaast is er de optie om meerdere leeftijden te verifieren. Wanneer 1 iemand niet de leeftijd check haalt kan een film nier worden gereserveerd / tickets worden gekocht of item worden gekocht.
=> Age verifier
